/**
 * The signing dialect a DELEGATED payer needs, and the third state.
 *
 * Two failure modes, both silent until the payment fails on-chain:
 *
 * 1. **Signing raw for an Alchemy SMA.** Once the EOA carries code, USDC checks
 *    ERC-1271 only, and raw ECDSA reverts with `0x151d90fe`. 14 of 14 delegated
 *    payers failed their escrow lock this way (2026-07-31).
 * 2. **Wrapping for a delegate that wants plain ECDSA.** Execution Market's
 *    `FeedbackDelegate` does `ECDSA.recover(hash, sig) == address(this)`. Every
 *    account that has rated through the facilitator's EIP-7702 feedback rail is
 *    pointed at it — so *the act of rating* would break the rater's next payment
 *    if the wrap were applied to "any delegated account".
 *
 * Both are the same mistake: treating "delegated" as one signature scheme.
 *
 * The vectors here are generated by the PYTHON SDK's `uvd_x402_sdk.erc7702`, not
 * invented for this file. A port compared only against itself proves nothing —
 * that is how three fabricated SEAL hashes once passed CI for months.
 */
import { describe, expect, it, vi, afterEach } from 'vitest';

import {
  DELEGATE_PREFIX,
  SMA_WRAP_TARGETS,
  delegateTarget,
  isDelegated,
  needsAccountWrap,
  replaySafeTypedData,
  resolveDelegation,
  rpcDelegationResolver,
  wrapSignature,
} from './erc7702.js';

const SMA = '0x69007702764179f14f51cdce752f4f775d74e139';
const FEEDBACK_DELEGATE = '0xa7ca33cae3c5890f25dfd08079db82701c9debc6';

afterEach(() => vi.unstubAllGlobals());

describe('delegateTarget', () => {
  // Vectors from the Python SDK.
  it('reads the target out of 7702 code', () => {
    expect(delegateTarget(`0x${DELEGATE_PREFIX}${SMA.slice(2)}`)).toBe(SMA);
    expect(delegateTarget(`0x${DELEGATE_PREFIX}${FEEDBACK_DELEGATE.slice(2)}`)).toBe(
      FEEDBACK_DELEGATE
    );
  });

  it('is null for a plain EOA and for non-7702 code', () => {
    // A plain EOA and a real contract are BOTH "no delegation", and neither may
    // be mistaken for one — reading a target out of ordinary bytecode would
    // apply a wrap against an implementation that never asked for it.
    expect(delegateTarget('0x')).toBeNull();
    expect(delegateTarget('0x6080604052')).toBeNull();
    expect(delegateTarget(null)).toBeNull();
    expect(delegateTarget(undefined)).toBeNull();
  });
});

describe('needsAccountWrap', () => {
  it('is true only for a known Alchemy SMA', () => {
    expect(needsAccountWrap(SMA)).toBe(true);
    expect(needsAccountWrap(SMA.toUpperCase())).toBe(true);
  });

  it('is FALSE for the FeedbackDelegate', () => {
    // The whole point of the 2026-08-25 fix. This delegate validates plain
    // ECDSA; wrapping for it produces an authorization that cannot settle, and
    // every rater on the facilitator's rail is delegated to it.
    expect(needsAccountWrap(FEEDBACK_DELEGATE)).toBe(false);
  });

  it('is false for a plain EOA', () => {
    expect(needsAccountWrap(null)).toBe(false);
    expect(needsAccountWrap(undefined)).toBe(false);
  });

  it('lists the SMA and nothing else', () => {
    expect(SMA_WRAP_TARGETS).toEqual([SMA]);
  });
});

describe('wrapSignature', () => {
  it('matches the Python SDK byte for byte', () => {
    // Generated by uvd_x402_sdk.erc7702.wrap_signature('0x' + 'ab'*65).
    expect(wrapSignature(`0x${'ab'.repeat(65)}`)).toBe(`0x0000000000ff00${'ab'.repeat(65)}`);
  });

  it('accepts a signature with or without the 0x', () => {
    expect(wrapSignature('ab'.repeat(65))).toBe(wrapSignature(`0x${'ab'.repeat(65)}`));
  });
});

describe('replaySafeTypedData', () => {
  it("uses the ACCOUNT's own domain, not the token's", () => {
    const td = replaySafeTypedData(`0x${'11'.repeat(32)}`, 8453, SMA);
    // Only chainId + verifyingContract: the two fields the account's typehash
    // declares. Adding name/version would change the domain separator and the
    // account would reject the signature.
    expect(td.domain).toEqual({ chainId: 8453, verifyingContract: SMA });
    expect(td.types).toEqual({ ReplaySafeHash: [{ name: 'hash', type: 'bytes32' }] });
    expect(td.message).toEqual({ hash: `0x${'11'.repeat(32)}` });
  });
});

describe('the third state', () => {
  /**
   * `null` is UNKNOWN and must never read as "not delegated". Collapsing the two
   * is how the original bug survived eight days: the resolver failed, the caller
   * read the falsy value as "plain EOA", and signed something that could never
   * settle.
   */
  it('is null with no resolver at all', async () => {
    expect(await isDelegated('0xabc', 'eip155:8453')).toBeNull();
    expect(await resolveDelegation('0xabc', 'eip155:8453')).toEqual({
      delegated: null,
      target: null,
    });
  });

  it('is null when the resolver throws', async () => {
    const boom = () => {
      throw new Error('rpc down');
    };
    expect(await resolveDelegation('0xabc', 'eip155:8453', boom)).toEqual({
      delegated: null,
      target: null,
    });
  });

  it('is null when the resolver returns garbage instead of an address', async () => {
    // A non-address string is not a verdict. Treating it as one would send a
    // wrap decision through on a value nobody validated.
    expect(await resolveDelegation('0xabc', 'eip155:8453', () => 'not-an-address')).toEqual({
      delegated: null,
      target: null,
    });
    expect(await resolveDelegation('0xabc', 'eip155:8453', () => '0xdeadbeef')).toEqual({
      delegated: null,
      target: null,
    });
  });

  it('carries the target through when the resolver names it', async () => {
    expect(await resolveDelegation('0xabc', 'eip155:8453', () => FEEDBACK_DELEGATE)).toEqual({
      delegated: true,
      target: FEEDBACK_DELEGATE,
    });
  });

  it('accepts a legacy boolean-only resolver, with no target', async () => {
    expect(await resolveDelegation('0xabc', 'eip155:8453', () => true)).toEqual({
      delegated: true,
      target: null,
    });
    expect(await resolveDelegation('0xabc', 'eip155:8453', () => false)).toEqual({
      delegated: false,
      target: null,
    });
  });
});

describe('rpcDelegationResolver', () => {
  it('returns the target for a delegated account', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: true,
        json: async () => ({ result: `0x${DELEGATE_PREFIX}${SMA.slice(2)}` }),
      }))
    );
    expect(await rpcDelegationResolver('https://rpc.example')('0xabc', 'eip155:8453')).toBe(SMA);
  });

  it('returns false for a readable plain EOA', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => ({ ok: true, json: async () => ({ result: '0x' }) })));
    expect(await rpcDelegationResolver('https://rpc.example')('0xabc', 'eip155:8453')).toBe(false);
  });

  it('returns null — not false — when every endpoint fails', async () => {
    // An unreadable chain is not a "not delegated" verdict. This is the
    // distinction the whole module exists to preserve.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('network');
      })
    );
    expect(
      await rpcDelegationResolver(['https://a.example', 'https://b.example'])('0xabc', 'eip155:8453')
    ).toBeNull();
  });

  it('rotates to the second endpoint when the first fails', async () => {
    let calls = 0;
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        calls += 1;
        if (calls === 1) throw new Error('first is down');
        return { ok: true, json: async () => ({ result: '0x' }) };
      })
    );
    expect(
      await rpcDelegationResolver(['https://a.example', 'https://b.example'])('0xabc', 'eip155:8453')
    ).toBe(false);
    expect(calls).toBe(2);
  });

  it('returns null with no endpoints', async () => {
    expect(await rpcDelegationResolver([])('0xabc', 'eip155:8453')).toBeNull();
  });
});
